version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-cdc
    environment:
      POSTGRES_DB: cdc_source
      POSTGRES_USER: cdc_user
      POSTGRES_PASSWORD: cdc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: >
      postgres 
      -c wal_level=logical 
      -c max_wal_senders=10 
      -c max_replication_slots=10
      -c shared_preload_libraries=pgoutput
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cdc_user -d cdc_source"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: mysql-cdc
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cdc_source
      MYSQL_USER: cdc_user
      MYSQL_PASSWORD: cdc_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
      - ./database/config/mysql-cdc.cnf:/etc/mysql/conf.d/mysql-cdc.cnf
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
      --expire-logs-days=7
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "cdc_user", "-pcdc_password"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mysql_data: 